import {
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  addDoc,
} from 'firebase/firestore';
import { db } from '../config/firebase';

/**
 * Get all documents from the database
 * @param {String} collectionName
 * @returns An array with all documents in the collection
 */
async function getAllDocs(collectionName) {
  const collectionReference = collection(db, collectionName);
  const documents = await getDocs(collectionReference);
  const docsArray = documents.docs.map((document) => {
    const data = document.data();
    return { id: document.id, ...data };
  });
  return docsArray;
}

/**
 * Get all documents from the database without the Id
 * @param {String} collectionName
 * @returns An array with all documents in the collection w/o the Id
 */
async function getAllDocsNoId(collectionName) {
  const collectionRef = collection(db, collectionName);
  const documents = await getDocs(collectionRef);
  const docsArray = documents.docs.map((document) => document.data());
  return docsArray;
}

/**
 * Get a document from the database
 * @param {String} collectionName
 * @param {String} id
 * @returns A document if it exists, otherwise returns false
 */
async function getDocById(collectionName, id) {
  const docRef = doc(db, collectionName, id);
  const docSnap = await getDoc(docRef);

  if (docSnap.exists()) {
    const data = docSnap.data();
    return { id: docSnap.id, ...data };
  }
  return false;
}

/**
 *
 * @param {Object} data Object with the data to be updated in the database
 * @param {String} collectionName Collection name
 * @param {String} id Document id
 * @returns Creates a document with the id provided if it doesn't exist
 */
async function createDocWithId(data, collectionName, id) {
  const docRef = doc(db, collectionName, id);
  const res = await setDoc(docRef, data);
  return res;
}

/**
 *
 * @param {Object} data Object with the data to be added to the database
 * @param {String} collectionName Collection name
 * @returns new document with autogenerated id
 */
async function createDoc(data, collectionName) {
  const collectionRef = collection(db, collectionName);
  const res = await addDoc(collectionRef, data);
  return res;
}

/**
 *
 * @param {String} id user id to be evaluated
 * @returns true if the user information is complete, false otherwise
 */
async function isSignupComplete(id) {
  const result = await getDocById('users', id);
  if (result) {
    return result?.username;
  }

  return false;
}

export {
  getAllDocs,
  getAllDocsNoId,
  getDocById,
  createDoc,
  createDocWithId,
  isSignupComplete,
};
